server:
  port: 8092

camel:
  component:
    servlet:
      mapping:
        context-path: '/*'

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    trust-all-packages: true  # Corresponds to trustAllPackages in XML


